In [1]:
# cargar dataset

import json
from pprint import pprint
dataset = list()
with open("../datasets/clasificado/comentarios_clasificados.json", "rt", encoding="utf-8") as arc:
    dataset = json.load(arc)

pprint(dataset[:5])

[{'aspectos': {'AvailabilityAndScalability': [],
               'Deployability': [],
               'Interoperability': [],
               'Maintainability': [],
               'Performance': ['good'],
               'Reliability': [],
               'Securability': []},
  'clas_modelo': {'AvailabilityAndScalability': None,
                  'Deployability': None,
                  'Interoperability': None,
                  'Maintainability': None,
                  'Performance': 1,
                  'Reliability': None,
                  'Securability': None},
  'clas_modelo_neutro': {'AvailabilityAndScalability': None,
                         'Deployability': None,
                         'Interoperability': None,
                         'Maintainability': None,
                         'Performance': 1,
                         'Reliability': None,
                         'Securability': None},
  'clas_tb': {'AvailabilityAndScalability': None,
              'Deployability': No

In [2]:
# dividir datasets en predicho_dos y esperado_dos y predicho_tres y esperado_tres
import numpy as np

predicho_dos = list()
esperado_dos = list()

# objeto con propiedades de los comentarios.
for elemento in dataset:
    # recorrer cada aspecto
    for aspecto in elemento["aspectos"]:
        # si el valor de la llave aspecto no es falsy
        if elemento["aspectos"][aspecto]:
            # agregamos el valor del sentimiento que predijo el clasificador a la lista de predichos
            if elemento["clas_modelo"][aspecto] == -1:
                predicho_dos.append([1,0])
            #elif elemento["clas_modelo"][aspecto] == 0:
            #    predicho_dos.append([0,1,0])
            else:
                predicho_dos.append([0,1])
            # agregamos el valor del sentimiento esperado del clasificador a la lista de esperados
            if elemento["clas_tb_no_neutro"][aspecto] == -1:
                esperado_dos.append([1,0])
            #elif elemento["clas_tb_no_neutro"][aspecto] == 0:
            #    esperado_dos.append([0,1,0])
            else:
                esperado_dos.append([0,1])

predicho_dos = np.array(predicho_dos)
esperado_dos = np.array(esperado_dos)
pprint(predicho_dos[:10])
pprint(esperado_dos[:10])

array([[0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0]])
array([[0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0]])


In [3]:
predicho_tres = list()
esperado_tres = list()

# objeto con propiedades de los comentarios.
for elemento in dataset:
    # recorrer cada aspecto
    for aspecto in elemento["aspectos"]:
        # si el valor de la llave aspecto no es falsy
        if elemento["aspectos"][aspecto]:
            # agregamos el valor del sentimiento que predijo el clasificador a la lista de predichos
            if elemento["clas_modelo_neutro"][aspecto] == -1:
                predicho_tres.append([1,0,0])
            elif elemento["clas_modelo_neutro"][aspecto] == 0:
                predicho_tres.append([0,1,0])
            else:
                predicho_tres.append([0,0,1])
            # agregamos el valor del sentimiento esperado del clasificador a la lista de esperados
            if elemento["clas_tb"][aspecto] == -1:
                esperado_tres.append([1,0,0])
            elif elemento["clas_tb"][aspecto] == 0:
                esperado_tres.append([0,1,0])
            else:
                esperado_tres.append([0,0,1])

predicho_tres = np.array(predicho_tres)
esperado_tres = np.array(esperado_tres)
pprint(predicho_tres[:10])
pprint(esperado_tres[:10])

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0]])
array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])


In [ ]:
# g-measure para dos clases
from sklearn.metrics.cluster import fowlkes_mallows_score
fowlkes_mallows_score([0, 0, 1, 1], [0, 0, 1, 1])